issue:
  - conditions:
      - labels.eq.bug
    rules:
      - body.eq./reproduction steps|to reproduce/i
    message: |
      As you have added a bug label please add your reproduction steps in the body using one of:
      * reproduction steps
      * to reproduce
      
pr:
  - rules:
      - title.eq./^\[WPS-[0-9]{1,4} - \]/
    message: "Titles should have the format [WPS-xxx] and a short description"
    
